rvm: 2.6

services: docker

jobs:
    fast_finish: true
    include:
        - name: "device"
          cache:
            directories:
              - $HOME/.rvm/
          before_install:
            - gem update --system # Fix https://github.com/rubygems/rubygems/pull/2780
            - gem install bundler
          install: cd device && bundle install && cd ..
          # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
          before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER
          script:
            - cd device
            - bundle exec foodcritic cookbooks/munger
            - bundle exec kitchen verify
        - name: "server"
          script:
            - docker build server