name: CI
on: [push, pull_request]
jobs:
  device:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: device
    - run: |
        cd device
        bundle exec foodcritic cookbooks/munger
        bundle exec kitchen verify
      continue-on-error: true
    - run: docker ps -a
    - run: docker ps -q | xargs -n 1 docker logs
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build server